### ISSUE TITLE
Arrays in page config?

### ISSUE THREAD

**Issue by ottob** [piranha/gostatic#29]
Thanks for a nice tool. One thing that I think would be useful is the possibility to define arrays in the page config. I have some pages that for instance need additional css and js files.

```
title: Main Page
morestyles: app1.css app2.css
----
```
Then in my header template I would do something like this:
```
{{ range .Other.Morestyles }}
      <link href="{{ . }}" rel="stylesheet">
{{ end }}
```

Does this seem reasonable or is there a better way of doing this with gostatic?

**Comment by piranha** [comment]
It does seem reasonable, but I'm not sure how to approach implementation. Right now the only array of strings possible is a list of tags, and others are a bit hard to implement because of Go's typing.

Not sure if you know Go, but if you look at [header struct](https://github.com/piranha/gostatic/blob/master/header.go#L13), you can see there are some predefined fields and everything else is put in `Other` (line 62 of same file) as a string. I could change `Other` signature to be `map[string]interface{}`, and try to parse based on value or a name (so we could say that to have array you have to write its name as `morestyles[]`) - but that sounds a bit scary + could fetch quite a bit of work.

After I wrote this rant I understood that I could just add `split` function to templates and you could do `{{ range split "," .Other.Morestyles }}`. :-) Stay tuned!

**Comment by piranha** [comment]
Enjoy new version! :-)

**Comment by ottob** [comment]
Perfect, thanks!

One other small thing I noted: below Quick Start in readme it says `site.html` I guess that should be `site.tmpl` now.

**Comment by piranha** [comment]
Yeah, `site.tmpl`, fixed now, thanks! :)
